"""add lead metadata

Revision ID: 60d6c21d0ea4
Revises: e0f25d9b6346
Create Date: 2026-08-17 16:08:06.674213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60d6c21d0ea4'
down_revision: Union[str, Sequence[str], None] = 'e0f25d9b6346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('ip_address', postgresql.INET(), nullable=True))
    op.add_column('leads', sa.Column('user_agent', sa.String(length=1024), nullable=True))
    op.add_column('leads', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'longitude')
    op.drop_column('leads', 'latitude')
    op.drop_column('leads', 'city')
    op.drop_column('leads', 'region')
    op.drop_column('leads', 'country')
    op.drop_column('leads', 'user_agent')
    op.drop_column('leads', 'ip_address')
    # ### end Alembic commands ###
