"""create widgets table

Revision ID: 8b24a9b7da8b
Revises: 8f1b0aa4fd3e
Create Date: 2026-08-16 15:23:37.605168

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b24a9b7da8b"
down_revision: str | Sequence[str] | None = "8f1b0aa4fd3e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "widgets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("public_key", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_widgets_public_key"), "widgets", ["public_key"], unique=True)
    op.create_index(op.f("ix_widgets_tenant_id"), "widgets", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_widgets_tenant_id"), table_name="widgets")
    op.drop_index(op.f("ix_widgets_public_key"), table_name="widgets")
    op.drop_table("widgets")
    # ### end Alembic commands ###
